# Generated by Django 5.1.3 on 2024-11-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='streaming',
            field=models.CharField(choices=[('F', 'Físico'), ('AK', 'Amazon Kindle')], max_length=2),
        ),
    ]
